[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nightingale"
version = "0.1.0"
description = "Nightingale - A Bird Call Classification Algorithm"
authors = [
    { name= "Ephraim Eckl" },
    { name= "David Pellhammer"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra -q"
testpaths = [
    "tests"
]